### ISSUE TITLE
The <base href> workaround breaks deployment to github.io in a non-obvious way

### ISSUE THREAD

**Issue by filiph** [dart-lang/stagehand#395]
I just deployed an AngularDart app to github.io using `peanut` — assuming it will Just Work as it did until now. But the [`<base href>` workaround](https://github.com/google/stagehand/blob/master/templates/web-angular/web/index.html#L5) in index.html breaks it.

The problem is that, by default, outside WebStorm's environment, base is set to `<base href="/">`. This break expectations because now the app that's deployed outside the root doesn't link properly to anything, including the generated JavaScript and the CSS.

1. App is deployed to `username.github.io/path`.
2. Link in `/path/index.html` refers to `main.dart.js`. This would normally resolve to `username.github.io/path/main.dart.js`.
3. But the `<base>` tag resets the path to `username.github.io/main.dart.js`.
4. There is no such file.
5. App doesn't load.

**Proposal**
Since this is the 'getting started' path, we should optimize for the "weekend fun project" use case. My assumption is that this almost never includes routing at first. I suggest:

1. Writing a short article explaining the workaround, including the code snippet.
2. Replacing the workaround code in the template with a `<!-- comment -->`, including a link to the article above.
2. Putting up large notices in the documentation wherever it talks about router. Link to the article.

WDYT @chalin @kwalrath ?

**Comment by kwalrath** [comment]
SGTM

**Comment by chalin** [comment]
That is essentially what we had before, so we'd be coming full circle. I don't mind doing so, but it might be helpful to first review how this came about.

Originally, we didn't set the `<base href>` in the template's `index.html`. Then came #360, to which most of us (including you, Matan and I), at least implicitly, [agreed](https://github.com/google/stagehand/issues/360#issuecomment-270550070). #360 may also have been prompted by the fact that the angular.io/ts folks decided to set the `<base href>` in their seed project too.

IMHO, dynamically initializing the `<base href>` can easily cater to the needs of both beginners (who are making their way through the AngularDart tutorial and other examples using WebStorm and/or `pub serve`), as well as week-end ngDart developers, as long as all parties deploy the content of the `build` folder rather than the `web` folder.

Anyhow, I agree that if we _must_ have but a _single_ AngularDart template, then it probably doesn't make sense to dynamically set `<base href>` by default.

I still think that the AngularDart docs need the equivalent of a web-angular-simple template. Maybe this is another argument in favor of #394.

**Comment by chalin** [comment]
@filiph - see proposal described in https://github.com/dart-lang/site-webdev/issues/591#issuecomment-298451157

**Comment by kwalrath** [comment]
@chalin can we close this?

**Comment by chalin** [comment]
Closed by #401 (the solution was to not set the `<base href>` in the template `index.html` file).
