### ISSUE TITLE
web-angular: add `test/app_test.html` in support of in-browser test monitoring

### ISSUE THREAD

**Issue by unicomp21** [dart-lang/stagehand#445]
Hitting 8081 for the generated test fails.

>[test] GET  → Could not find asset meetme|test.

**Comment by 4cm4k1** [comment]
I show the same issue. I turned on verbose reporting:
```
FINE: Instance of 'BarbackServer' GET 
    | Not Found
ERR : [test] GET  → Could not find asset anthony_codes|test.
```

**Comment by kwalrath** [comment]
@kevmoo could you please assign this to @chalin and give me admin permissions for this repo?

**Comment by kevmoo** [comment]
@chalin already has write permissions – why is admin required? (Paid to be paranoid 😄 )

**Comment by kwalrath** [comment]
Admin permissions are for me, not Patrice. :)

**Comment by kevmoo** [comment]
Done! – deleting this silly

**Comment by chalin** [comment]
Unless you are doing some extra setup, this feature isn't yet supported "out of the box" by the generated Angular project.

We've been wanting to add support for in-browser test monitoring since April for the AngularDart doc examples (via https://github.com/dart-lang/site-webdev/pull/575), but we've had some pending unresolved issues.  Anyhow, I've just committed 575 and as soon as we've addressed all pending issues, I'll update the web-angular template here.

I'll use this issue to track progress (but I'll adjust the title).

cc @kwalrath @matanlurey

**Comment by chalin** [comment]
Just to be clear: this works for me (after setting up an appropriate test `*.html` page). I.e., after visiting, say, http://localhost:8081/app_test.html, in the browser console I see:
> 00:00: All tests passed!

and no GET errors reported by pub. (You might see "EXCEPTION: Bad state: Cannot fire new event" in the JS console, but we're aware of that issue and it doesn't seem to prevent the tests from executing.)

**Comment by chalin** [comment]
As I mentioned in the previous comment, https://github.com/dart-lang/stagehand/issues/445#issuecomment-327787205, this worked for me so I'll close this issue for now. In-browser testing will work out-of-the-box with Angular 5.
