### ISSUE TITLE
Angular: remove the dev-override on pageloader

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/stagehand#487]
https://github.com/dart-lang/stagehand/blob/7d2a11d170ea2b8aa743f3eff33a6891ef73ab9a/templates/web-angular/pubspec.yaml#L21-L27

**Comment by chalin** [comment]
I'd qualify it as "manual" rather than "hacky" :).

It just occurred to me that the current pageloader package could actually allow us to test ACX apps, ... something that we could not do with the pageloader v2. (I haven't had the time to try that, but it has been on my to-do list for a little while.)

**Comment by kevmoo** [comment]
Just chatted w/ angular folks. We're going to remove the test bits that require this workaround. @kwalrath to run w/ this
