### ISSUE TITLE
Import and use individual angular_components libraries and components

### ISSUE THREAD

**Issue by chalin** [dart-lang/stagehand#496]
cc @kwalrath

**Comment by chalin** [comment]
@kwalrath, @kevmoo, @nshahan  - while I can import individual libraries and components:

- In `templates/web-angular/lib/src/todo_list/todo_list_component.dart` I replaced `materialDirectives` with individually listed ACX directives, but then when I attempt to run tests I get the following issue:

  ```nocode
  Running tests...
  00:00 +0 -1: test/app_test.dart: heading [E]
    Assertion failed: "No value accessor for () or you may be missing formDirectives in your directives list."
    dart:sdk_internal                                                               assertFailed
    package:angular_forms/src/directives/shared.dart 25:28                          setUpControl
    package:angular_forms/src/directives/ng_model.dart 127:5                        ngOnInit
    package:__projectName__/src/todo_list/todo_list_component.template.dart 162:19  detectChangesInternal
    package:angular/src/core/linker/app_view.dart 407:7                             detectChanges
    package:__projectName__/app_component.template.dart 97:16                       detectChangesInternal
    package:angular/src/core/linker/app_view.dart 407:7                             detectChanges
    package:__projectName__/app_component.template.dart 331:16                      detectChangesInternal
    package:angular/src/core/linker/app_view.dart 407:7                             detectChanges
    package:angular/src/core/linker/view_ref.dart 106:12                            detectChanges
  ...
  ```

  But I am also including `formDirectives`, so I'm unsure what I am missing. Also note that the angular_analyzer plugin isn't reporting any issues.

- In `templates/web-angular/lib/app_component.dart` I seem to require `materialProviders` so the app ends up importing all of ACX. (I haven't found a list of individual providers that have worked yet; regardless, I end up having imports like `package:angular_components/utils/browser/dom_service/dom_service.dart`. Is this what we want to encourage users to do?)

**Comment by kevmoo** [comment]
With the new compiler, I think we're okay importing everything – it's smart
enough to drop what's not needed...

**Comment by kwalrath** [comment]
@nshahan can you confirm that it's OK to import the big library rather than individual component libraries?

**Comment by nshahan** [comment]
It depends on what you are trying to optimize. If you want a simple experience then you can import the single file that brings in every component into your app.

If you want the best build times and smallest possible output from dart2js then you should only import what you are using. Even the best tree shaking can't prove that are are not going to use some code when we are dealing with hash tables with dynamic types etc. 

Based on @jakemac53 comments in https://github.com/dart-lang/angular_components/issues/242 I believe the development experience with a modular compiler like DDC is better when you are importing only the files you are using.

We can try running some benchmarks to see the difference, but I don't have any numbers at the moment.

**Comment by matanlurey** [comment]
To clarify, from an AngularDart perspective:

* If you are using the new `runApp` (and not `runAppLegacy`) it doesn't effect code-size.
* However, it might effect compilation time (iterating through 100s of items per component)

I'd recommend _not_ using these giant lists of components, anywhere.

Its a little less terrible to use small lists of tightly connected things, for example `formDirectives`.

**Comment by MichaelRFairhurst** [comment]
It looks like the error is related to having the wrong providers. Unfortunately we can't validate providers/DI, I saw somewhere a proof that it would be an NP-hard problem to try :( I think it also would be a whole-app analysis rather than a file-level analysis, which we don't have any infra for. That said, NP-hard for a small N isn't actually always that hard. So some day I may want to sit down with people to better understandwhat type of validation I'd have to do.

In the meantime, looks like there are a few questions in this thread:

* Should you import giant directives lists?
* Should you import giant providers lists?
* What subset of directives and providers will work and how do users know that for any given directive?
* Can we get a better error message in the compiler for this case?

Wish my plugin could catch this, but if I follow correctly so far, I don't think it can :(

**Comment by chalin** [comment]
@nshahan - I was just about to ask for a nice short list of material input directives, but it's there already! :) https://github.com/dart-lang/angular_components/blob/master/lib/material_input/material_input.dart#L24-L32

**Comment by MichaelRFairhurst** [comment]
Hmm, well if it was a missing directive, I may be able to provide support.

Its probably not really feasible with angular as written, since directives are cross-linked via the DI system.

However, maybe if there were a new annotation like `@OnElement` then youd be able to do:

```
@Component(...)
class A {
  A(@OnElement ValueAccessor);
  ...
}
@Directive(...)
class MyValueAccessor extends ValueAccessor {
  ...
}
```

template:
```
<a-component with-no-value-accessor></a-component>
```

then I'd be able to flag something like, _You're using component "A" which requires a directive on the element that implements "ValueAccessor", but no such directive exists. Try checking for missing directives in your component definition, misspelled attributes, or check API docs for which directives implement "ValueAccessor"_.

That said, its not exactly a great error message. But this I believe is the type of work I'd need to do to solve https://github.com/dart-lang/angular_analyzer_plugin/issues/233

I don't think I could do this with the way that angular is written, since for any set of injected dependencies, I have no real way of knowing whether they are base classes that should be implemented by directives or not.

Worse, in this case, it looks like it injects an `@Optional List<ControlValueAccessor>` which is two more reasons why I wouldn't be able to catch this (I will likely assume empty lists are OK, and I'll certainly assume missing `@Optional`s is ok, in whatever type of implementation I would throw together).

If everyone on this thread thinks I'm making sense and it would provide value, I can open an issue in the angular repo.

**Comment by chalin** [comment]
I can see how this would be a tricky situation to detect. I'll @nshahan and others comment.
