### ISSUE TITLE
Exhausted heap space, using 'stagehand web-angular'

### ISSUE THREAD

**Issue by ichengde** [dart-lang/stagehand#545]
### env:
ubuntu 16.04
Dart VM version: 2.0.0-dev.64.1 (Unknown timestamp) on "linux_x64"

### document source:
https://webdev-dartlang-org-dev.firebaseapp.com/guides/get-started#4-create-a-web-app
### step:
stagehand web-angular
### console output result:
chegde@chegde://home/chegde/workspace/dart/quickstart$ stagehand web-angular
Exhausted heap space, trying to allocate 48 bytes.
Exhausted heap space, trying to allocate 10160 bytes.

When i look up stagehand project, 
https://github.com/dart-lang/stagehand/blob/ef63097caa0187565b3d155a349a0cf9288a97f3/lib/stagehand.dart#L16
it works.

So the command that is 'stagehand web-angular' don't work. How to resolve it?

**Comment by CarnivalRaid** [comment]
Hello there. I do not have the same output on stagehand web-angular, but it eats my entire ram and goes into swap. Processor is in full. 

I would also add that after stagehand, when doing "webdev serve" is eating alot of RAM (2gigs).
WattOS(Ubuntu 16.04.4 LTS Xenial, i5 dual core, 4Gb RAM, 3,4GB RAM free to use.) So ofc swapping for an empty angular app is too much.

**Comment by ichengde** [comment]
https://github.com/dart-lang/pub/issues/1936
@CarnivalRaid you are right.

**Comment by chalin** [comment]
Hi. As mentioned here https://github.com/dart-lang/stagehand/issues/543#issuecomment-399668142, can you instead try running:

```console
> pub global run stagehand web-angular
```

**Comment by ichengde** [comment]
@chalin  OK. So it is the document problem? thank, i closed it.

**Comment by ichengde** [comment]
@chalin  Yes. In the issue description, i had said this. I found it in the code source. but it is different from the document, and the way of the document causes a error. So i open this issue. the rest of problem is that the RAM size is too much during `webdev serve`.

**Comment by CarnivalRaid** [comment]
Hey @ichengde, @chalin . It works great with:
>pub global run stagehand web-angular
>pub global run webdev serve

The problem persists with RAM consumption and disk scratching(in my case with 3.4G RAM to freely use) but also with CPU, where mine sits at 97% chocking the system.
Yes 3.4G is low RAM(this is a traveling laptop for strictly console programming).

But when scratching and RAM consumption happens, it enters a vicious circle with CPU close 100%. The more cpu using the less the ram will get free again fast, and the less ram and scratch the more cpu usage.

Cheers, great day all.

**Comment by chalin** [comment]
@CarnivalRaid: thanks for the feedback. As is mentioned on the [webdev page](https://webdev-dartlang-org-dev.firebaseapp.com/tools/webdev) (and you might know already), the first time you run webdev will be "the slowest. After that, assets are cached on disk and incremental builds are much faster."

So, for example, if you run `webdev build --no-release --output web:build`, and then `webdev serve` the serve command should be quick, and CPU usage should be low/moderate (or at least only briefly spike). Is this the behavior you are seeing?

**Comment by CarnivalRaid** [comment]
@chalin Hi there. The differences are huge. Way way better :). 
I ran:
> pub global run webdev build --no-release --output web:build
It took much much less time and cpu.
[INFO] Reading cached asset graph completed, took 1.4s
[INFO] Checking for updates since last build completed, took 2.9s
[INFO] Running build completed, took 1.0s
[INFO] Caching finalized dependency graph completed, took 688ms
[INFO] Creating merged output dir `build` completed, took 13.9s
[INFO] Writing asset manifest completed, took 14ms
[INFO] Succeeded after 15.7s with 0 outputs (0 actions)


> pub global run webdev serve
[INFO] Setting up file watchers completed, took 46ms
[INFO] Waiting for all file watchers to be ready completed, took 451ms
[INFO] Reading cached asset graph completed, took 1.5s
[INFO] Checking for updates since last build completed, took 947ms
[INFO] Running build completed, took 998ms
[INFO] Caching finalized dependency graph completed, took 662ms
[INFO] Succeeded after 1.7s with 0 outputs (0 actions)
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081

My I5 spiked at a maximum of 30%  and Idle at 1% which is really awsome and really fast reading the cache. And now my little mobile lenovo is feeling good, RAM wise is way way better.

Second run of >webdev serve
[INFO] Setting up file watchers completed, took 54ms
[INFO] Waiting for all file watchers to be ready completed, took 524ms
[INFO] Reading cached asset graph completed, took 1.6s
[INFO] Checking for updates since last build completed, took 1.0s
[INFO] Running build completed, took 1.2s
[INFO] Caching finalized dependency graph completed, took 573ms
[INFO] Succeeded after 1.7s with 0 outputs (0 actions)
Serving `web` on http://localhost:8080
Serving `test` on http://localhost:8081

As you pointed, because of cache, things are even better. 900MB RAM, CPU 30%, IDle 1%.

Hope it helps. If I am beeing too loose on texting please tell me :).
Great day, and thank you for the solution.

**Comment by CarnivalRaid** [comment]
I would like to add as @kevmoo said, upgrading to -dev.65 solves the snapshot 1.1 problem, no need for 
>pub global run
instead normal usage with stagehand and webdev directly.

I would also like to add  - @kevinmoo @chalin - that now webdev serve executed (with dev.65) a second time was much much faster, and only 500M vs 900M(with previous build). Great job guys.
Thank you both.

**Comment by chalin** [comment]
Thanks for the detailed feedback, and confirming that it all works even better with 2-dev.65!
