### ISSUE TITLE
Stagehead 3.3.2 not supported dart 2.3

### ISSUE THREAD

**Issue by leeashley** [dart-lang/stagehand#617]
I try to create a flutter web project using Dart and Flutter extensions, both, v3.2.0 on VSCode.
Output: flutter-web-preview] pub global run stagehand flutter-web-preview
stagehand 3.3.2 doesn't support Dart 2.3.0-dev.0.5.flutter-a1668566e5.
exit code 65

Flutter version: 1.5.4-hotfix.2
Dart SDK version: 2.4.0

**Comment by zaman5450** [comment]
fFor me same issue  [flutter-web-preview] pub global run stagehand flutter-web-preview
stagehand 3.3.2 doesn't support Dart 2.3.0-dev.0.5.flutter-a1668566e5.
exit code 65

**Comment by devmvk** [comment]
today i tried to create new flutter web project using VSCode and i received this same error

**Comment by leeashley** [comment]
> today i tried to create new flutter web project using VSCode and i received this same error
> 
> ```
> flutter-web-preview] pub global run stagehand flutter-web-preview
> stagehand 3.3.2 doesn't support Dart 2.3.0-dev.0.5.flutter-a1668566e5.
> exit code 65
> ```

I decided to downgrade the stagehand, I used this command:
pub downgrade stagehand 3.3.1

**Comment by leeashley** [comment]
> today i tried to create new flutter web project using VSCode and i received this same error
> 
> ```
> flutter-web-preview] pub global run stagehand flutter-web-preview
> stagehand 3.3.2 doesn't support Dart 2.3.0-dev.0.5.flutter-a1668566e5.
> exit code 65
> ```

I decided to downgrade the stagehand, I used this command:
pub downgrade stagehand 3.3.1

**Comment by kevmoo** [comment]
https://github.com/dart-lang/stagehand/pull/614#issuecomment-504213014 – I asked why we updated the deps here!!!

CC @domesticmouse

**Comment by kwalrath** [comment]
These kinds of breakages seem like something that testing should be able to catch.

**Comment by kevmoo** [comment]
> These kinds of breakages seem like something that testing should be able to catch.

But if you bump the min SDK tested on Travis, you loose these tests. 😕

**Comment by kwalrath** [comment]
> > These kinds of breakages seem like something that testing should be able to catch.
> 
> But if you bump the min SDK tested on Travis, you lose these tests. 😕

Maybe we need a different min SDK for flutter?

**Comment by domesticmouse** [comment]
Why is the VSCode plug in using the flutter sdk to run stagehand? That seems wrong, given stagehand is meant for command line and web apps. I’d say this is a bug for the VSCode plug-in to fix, not stagehand. This will happen again when we update for 2.5.

**Comment by domesticmouse** [comment]
We just updated Flutter stable to 1.7.8+hotfix.2 which comes with Dart 2.4.0, so this should now work. Please update Flutter and re-test.

**Comment by DanTup** [comment]
I discovered this issue yesterday in Dart-Code's own CI tests (we run them all with both Stable + Dev branches of Flutter + Dart and the CI script always installs the latest stagehand). I saw Flutter was close to being released so figured it might not be a problem this time round (I also thought the chances of a user hitting it were lower than they apparently turned out to be because it requires activating stagehand via the new Dart prior to trying to run it for Flutter).

> Why is the VSCode plug in using the flutter sdk to run stagehand? That seems wrong, given stagehand is meant for command line and web apps.

VS Code only tracks a single Dart SDK in a session and if you have a Flutter project open (or are trying to run a Flutter command) it'll always be the one from Flutter. Even if we tracked a standalone Dart SDK too, I don't think it entirely solves this issue - it's not guaranteed that a users standalone Dart SDK is newer than the Flutter one either (so we could end up having the problem the other way around - I tend to update my standalone Dart infrequently, but Flutter frequently). Originally the stagehand integration was only used for the Dart projects so this didn't come up.

I think the easiest way to avoid this is to avoid revving Pub package SDK versions until Flutter stable updates too, but I don't know if that's feasible (I think that's a good idea for Pub packages generally though). Another option could be to lock the Stagehand version in VS Code and manually rev that version myself when I know it works with both versions (though this could reduce the frequency that users got updates).

**Comment by domesticmouse** [comment]
Thanks @DanTup for the commentary on the underlying issues here. Given this state of affairs I'll add an entry to Stagehand's test matrix that tracks Flutter's stable SDK version. Please don't pin Stagehand version in Dart-Code. =)

**Comment by DanTup** [comment]
Cool, that sounds like the simplest fix here (albeit something that each package we use needs to do individually - fortunately there aren't many (stagehand/webdev/devtools)).

**Comment by leeashley** [comment]
Resolved.
Fix: Update Flutter SDK to v1.7.8+hotfix.2-stable.
